# Generated by Django 3.2.4 on 2021-06-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_history_chosed_theme"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="phone_number",),
        migrations.RemoveField(model_name="customuser", name="send_text_message",),
    ]
