apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: {{ .Values.monitoring_namespace}}
spec:
  selector:
    app: git-clone-cd
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: cadvisor
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: nodeexporter
    protocol: TCP
    port: 9100
    targetPort: 9100
  - name: pushgateway
    protocol: TCP
    port: 9091
    targetPort: 9091
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090
  type: LoadBalancer
