apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alertmanager-config
  namespace: {{ .Values.namespace }}
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: {{ .Secrets.email_username }}
      smtp_auth_username: {{ .Secrets.email_username }}
      smtp_auth_password: {{ .Secrets.email_password }}
      smtp_require_tls: true
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h 
      receiver: 'email-config'
    receivers:
    - name: 'email-config'
      email_configs:
      - to: {{ .Secrets.email_username }}