apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alertmanager-config
  namespace: {{ .Values.namespace }}
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h 
      receiver: 'email-config'
    receivers:
    - name: 'email-config'
      email_configs:
      - to: 'nuno.ricardo.mars@gmail.com'