apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-alertmanager-config
  namespace: {{ .Values.namespace }}
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 1m

    route:
      receiver: 'gmail-notifications'

    receivers:
    - name: 'gmail-notifications'
      email_configs:
      - to:
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-alertmanager-smtp-secret
              key: email_username
        from:
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-alertmanager-smtp-secret
              key: email_username
        smarthost: 'smtp.gmail.com:587'
        auth_username:
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-alertmanager-smtp-secret
              key: email_username
        auth_identity:
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-alertmanager-smtp-secret
              key: email_username
        auth_password:
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-alertmanager-smtp-secret
              key: email_password
        send_resolved: true
        require_tls: true
