apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-django-media-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  mountOptions:
    - tls  
  nfs:
    path: /
    server: fs-048cb0d091a9bf233.efs.eu-west-3.amazonaws.com