apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-back-service-lb"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Release.Name }}-back-deployment"
spec:
  selector:
    app: "{{ .Release.Name }}-back-deployment"
  type: ClusterIP # ou NodePort
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 5000
