apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-back-service-lb"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Release.Name }}-back-deployment"
spec:
  selector:
    app: "{{ .Release.Name }}-back-deployment"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30080
      nodePort: 30080
  type: NodePort
  healthCheckNodePort: 30080
  healthCheckPath: /healthz