apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-back-deployment"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-back-deployment"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-back-deployment"
    spec:
      imagePullSecrets:
        - name: localregistrysecret
      containers:
      - name: "{{ .Release.Name }}-back-container"
        image: "ghcr.io/nunomars/tp/{{ .Values.backendlabel }}:{{ .Values.defaultTag }}"      
        ports:
        - containerPort: 5000
        command:
        - "/bin/sh"
        - "-c"
        args:
        - "python3 manage.py migrate && python3 manage.py loaddata db.json"
        ports:
        - containerPort: 5000
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-postgresql-credentials"
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-postgresql-credentials"
                key: POSTGRES_PASSWORD        
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-backend-cm"
        volumeMounts:
            - name: media-volume
              mountPath: /app/media    
        resources: 
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-django-media-pvc
status: {}
