apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-back-service-lb"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Release.Name }}-back-deployment"
spec:
  selector:
    app: "{{ .Release.Name }}-back-deployment"
  ports:
    - protocol: TCP
      port: 80  # Port sur lequel le service écoute
      targetPort: 5000  # Port sur lequel vos pods écoutent
      nodePort: 30080  # Port NodePort
  type: LoadBalancer