apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-django-media-pv
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/media"