apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-django-media-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: gp2
  volumeMode: Filesystem

  awsElasticBlockStore: {}