apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-site-voyance-lb"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Release.Name }}-back-deployment"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Spécifie le type de load balancer AWS
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # Définit si le load balancer est interne ou externe
    service.beta.kubernetes.io/aws-load-balancer-name: "site-voyance-lb"  # Nom explicite du load balancer
spec:
  selector:
    app: "{{ .Release.Name }}-back-deployment"
  ports:
    - protocol: TCP
      port: 80  # Port sur lequel le service écoute
      targetPort: 5000  # Port sur lequel vos pods écoutent
  type: LoadBalancer