apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-back-deployment
  namespace: site-voyance-prod
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-back-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-back-deployment
    spec:
      containers:
      - name: {{ .Release.Name }}-back-container
        image: "ghcr.io/nunomars/tp/{{ .Values.backendlabel }}:{{ .Values.defaultTag }}"
        command:
        - "/bin/sh"
        - "-c"
        args:
        - "python3 manage.py migrate && python3 manage.py loaddata db.json"
        ports:
        - containerPort: 5000
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: .....
              key: ....
        - name: Db credentials        
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password          
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-backend-cm"
        volumeMounts:
        - name: media-volume
          mountPath: /app/media    
        resources: 
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-django-media-pvc
status: {}
