apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
      - name: cadvisor-container
        image: google/cadvisor:latest
        ports:
        - containerPort: 8080