apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-frontend-cm"
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      location / {
        proxy_pass {{ .Release.Name }}-back-service.{{ .Values.namespace }}.svc.cluster.local:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }