apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-backend-cm"
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "http://{{ .Release.Name }}-postgresql-service.{{ .Values.namespace }}.svc.cluster.local"
  ENV: "{{ .Values.environement }}"
  DB_PORT: "5432"
