apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-backend-cm"
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "{{ .Release.Name }}-postgresql-service"
  ENV: "{{ .Values.environement }}"
  DB_PORT: "5432"
  ENVIROMENT: "{{ .Values.environement }}"
  REDIS_HOST: "{{ .Release.Name }}-redis-service"
  REDIS_PORT: "6379"
  JAEGER_AGENT_HOST: "{{ .Release.Name }}-jaeger-service"
  JAEGER_AGENT_PORT: "6831"
  JAEGER_SERVICE_NAME: "site-voyance"
  