apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-postgresql-backup
spec:
  schedule: "0 3 * * *" # se lance toutes les nuits à 3h
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:14.5
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -U $POSTGRES_USER -d $POSTGRES_DB > /backup/backup.sql
            env:
            - name: POSTGRES_DB
              value: {{ .Values.POSTGRES_DB }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-postgresql-credentials"
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-postgresql-credentials"
                  key: POSTGRES_PASSWORD
            volumeMounts:
            - name: backup
              mountPath: /backup
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: {{ .Release.Name }}-backup-pvc
          restartPolicy: OnFailure