apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-nginx-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-nginx-deployment"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-nginx-deployment"
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
  volumeMounts:
  - name: nginx-config
    configMap:
      name: "{{ .Release.Name }}-frontend-cm"
    items:
    - key: nginx.conf
      path: nginx.conf