apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana-deployment
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-datasources
        configMap:
          name: {{ .Release.Name }}-grafana-datasources