apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: {{ .Values.monitoring_namespace}}
spec:
  selector:
    app: git-clone-cd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  - protocol: TCP
    port: 8080
    targetPort: 8080
  - protocol: TCP
    port: 9090
    targetPort: 9090
  - protocol: TCP
    port: 9091
    targetPort: 9091
  - protocol: TCP
    port: 9093
    targetPort: 9093
  type: LoadBalancer