apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: prometheus-container
        image: prom/prometheus:v2.48.0
        volumeMounts:
        - name: prometheus-data
          mountPath: /prometheus
        command:
        - '/bin/prometheus'
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--storage.tsdb.retention.time=200h'
        - '--web.enable-lifecycle'
        ports:
        - containerPort: 9090
      - name: grafana-container
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
      - name: cadvisor-container
        image: google/cadvisor:latest
        ports:
        - containerPort: 8080
      - name: nodeexporter-container
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
      - name: pushgateway-container
        image: prom/pushgateway:latest
        ports:
        - containerPort: 9091
      - name: alertmanager-container
        image: prom/alertmanager:latest
        ports:
        - containerPort: 9093
      volumes:
      - name: prometheus-data
        emptyDir: {}