apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc  
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi