apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: {{ .Release.Name }}-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgresql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgresql
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9187"
    spec:
      containers:
      - name: postgresql
        image: postgres:14.5
        env:
        - name: POSTGRES_DB
          value: {{ .Values.POSTGRES_DB }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-postgresql-credentials"
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-postgresql-credentials"
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      - name: postgres-exporter
        image: wrouesnel/postgres_exporter
        ports:
        - name: exporter
          containerPort: 9187
        env:
        - name: DATA_SOURCE_NAME
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@localhost:5432/$(POSTGRES_DB)?sslmode=disable
      volumes:
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgresql-pvc