apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-alert-rules
  namespace: {{ .Values.namespace }}
data:
  alert.rules.yml: |
    groups:
    - name: example
      rules:
      - alert: HighErrorRate
        expr: job:request_error_rate_per_second > 0.5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High request error rate"
          description: "Requests are failing at a high rate. Investigate immediately."
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Service is down"
          description: "The service is not responding. Check the service status."