apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.monitoring_namespace }}
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer