apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus-service
spec:
  selector:
    app: prometheus
  type: LoadBalancer  
  ports:
    - protocol: "http"
      port: 80
      protocol: TCP
      targetPort: 9090
  