apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'alertmanager'
        static_configs:
          - targets: ['http://{{ .Release.Name }}-alertmanager.{{ .Values.namespace}}.svc.cluster.local:9093']