apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway-container
        image: prom/pushgateway:latest
        ports:
        - containerPort: 9091