apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-deployment
  labels:
    app: {{ .Release.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9121"
    spec:
      containers:
      - name: {{ .Release.Name }}-redis
        image: redis:latest
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-postgresql-credentials"
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 6379
      - name: redis-exporter
        image: oliver006/redis_exporter
        ports:
        - name: exporter
          containerPort: 9121
        env:
        - name: REDIS_ALIAS
          value: localhost
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-postgresql-credentials"
              key: POSTGRES_PASSWORD