# Generated by Django 4.1.2 on 2022-12-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ball8", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sentences",
            new_name="SentencesFr",
        ),
    ]
