# Generated by Django 4.1.2 on 2022-12-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ball8", "0002_rename_sentences_sentencesfr"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentencesEn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField()),
                (
                    "sentence_polarity",
                    models.CharField(
                        choices=[
                            ("Positif", "Positif"),
                            ("Negatif", "Negatif"),
                            ("Neutral", "neutral"),
                        ],
                        default="Positif",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
