appname: "tarot-app-prod"
backendlabel: "tarot-prod"
replicas: 1
namespace: "taror-app-prod"
cmname: "tarot-app-cm-prod"
environement: "prod"
projname: "tarot-prod"
pvcname: "tarot-app-pvc-prod"
defaultTag: latest
