appname: "site-voyance-prod"
backendlabel: "tarot-prod"
replicas: 1
namespace: "site-voyance-prod"
cmname: "tarot-app-cm-prod"
environement: "prod"
projname: "site-voyance-prod"
pvcname: "tarot-app-pvc-prod"
defaultTag: latest
