appname: "site-voyance-prod"
backendlabel: "tarot-prod"
replicas: 3
namespace: "site-voyance-prod"
cmname: "tarot-app-cm-prod"
environement: "prod"
projname: "site-voyance-prod"
pvcname: "tarot-app-pvc-prod"
defaultTag: latest
host: "site-voyance-prod.devops.oclock.school"
POSTGRES_DB: "VoyanceDB"
monitoring_namespace: "monitoring"
efs:
  dns_name: "fs-09e74fe30f87574e3.efs.eu-west-3.amazonaws.com"
  storage_capacity: "5Gi"
  storage_class: "efs-storage-class"
  access_mode: "ReadWriteMany"

alertmanager_url: "http://alertmanager.monitoring.svc.cluster.local:9093"
