appname: "site-voyance-prod"
backendlabel: "tarot-prod"
replicas: 3
namespace: "site-voyance-prod"
cmname: "tarot-app-cm-prod"
environement: "prod"
projname: "site-voyance-prod"
pvcname: "tarot-app-pvc-prod"
defaultTag: latest
host: "site-voyance-prod.devops.oclock.school"
POSTGRES_DB: "VoyanceDB"
monitoring_namespace: "monitoring"
imageVersions:
  prometheus: prom/prometheus:v2.48.0
  alertmanager: prom/alertmanager:v0.26.0
  nodeExporter: prom/node-exporter:v1.7.0
  cadvisor: gcr.io/cadvisor/cadvisor:v0.47.2
  grafana: grafana/grafana:10.2.2
  pushgateway: prom/pushgateway:v1.6.2
  caddy: caddy:2.7.5

