# Generated by Django 4.1.2 on 2024-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsesBookEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_title', models.TextField()),
                ('sentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsesBookEs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_title', models.TextField()),
                ('sentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsesBookFr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_title', models.TextField()),
                ('sentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsesBookPt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_title', models.TextField()),
                ('sentence', models.TextField()),
            ],
        ),
    ]
