# Generated by Django 4.1.2 on 2022-12-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsesBookEs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence_title", models.TextField()),
                ("sentence", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ResponsesBookFr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence_title", models.TextField()),
                ("sentence", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ResponsesBookPt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence_title", models.TextField()),
                ("sentence", models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name="ResponsesBook",
            new_name="ResponsesBookEn",
        ),
    ]
