# Generated by Django 4.1.2 on 2024-03-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MajorArcana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=50)),
                ('card_signification_gen', models.TextField(default='card_signification_gen')),
                ('card_signification_warnings', models.TextField(default='card_signification_warnings')),
                ('card_signification_love', models.TextField(default='card_signification_love')),
                ('card_signification_work', models.TextField(default='card_signification_work')),
                ('card_image', models.ImageField(upload_to='MajorArcanaCards')),
                ('card_polarity', models.CharField(choices=[('Positif', 'Positif'), ('Negatif', 'Negatif'), ('Neutral', 'neutral')], default='Positif', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RightDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clairvoyance.majorarcana')),
            ],
        ),
        migrations.CreateModel(
            name='LeftDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clairvoyance.majorarcana')),
            ],
        ),
    ]
