# Generated by Django 3.2.4 on 2021-10-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clairvoyance', '0002_alter_majorarcana_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clairvoyance.majorarcana')),
            ],
        ),
        migrations.CreateModel(
            name='LeftDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clairvoyance.majorarcana')),
            ],
        ),
    ]
