# Generated by Django 4.1.2 on 2022-12-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clairvoyance", "0004_rename_card_name_majorarcana_card_name_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="majorarcana",
            name="card_name_en",
            field=models.CharField(default="en", max_length=50),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_name_es",
            field=models.CharField(default="es", max_length=50),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_name_pt",
            field=models.CharField(default="pt", max_length=50),
        ),
        migrations.AlterField(
            model_name="majorarcana",
            name="card_signification_gen_fr",
            field=models.TextField(default="fr"),
        ),
        migrations.AlterField(
            model_name="majorarcana",
            name="card_signification_warnings_fr",
            field=models.TextField(default="pt"),
        ),
    ]
