# Generated by Django 4.1.2 on 2022-12-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clairvoyance",
            "0005_majorarcana_card_name_en_majorarcana_card_name_es_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_gen_en",
            field=models.TextField(default="en"),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_gen_es",
            field=models.TextField(default="es"),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_gen_pt",
            field=models.TextField(default="pt"),
        ),
    ]
