# Generated by Django 4.1.2 on 2022-12-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clairvoyance", "0006_majorarcana_card_signification_gen_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_love_en",
            field=models.TextField(default="en"),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_love_es",
            field=models.TextField(default="es"),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_love_pt",
            field=models.TextField(default="pt"),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_warnings_en",
            field=models.TextField(default="en"),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_warnings_es",
            field=models.TextField(default="es"),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_warnings_pt",
            field=models.TextField(default="pt"),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_work_en",
            field=models.TextField(default="en"),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_work_es",
            field=models.TextField(default="es"),
        ),
        migrations.AddField(
            model_name="majorarcana",
            name="card_signification_work_pt",
            field=models.TextField(default="pt"),
        ),
        migrations.AlterField(
            model_name="majorarcana",
            name="card_signification_love_fr",
            field=models.TextField(default="fr"),
        ),
        migrations.AlterField(
            model_name="majorarcana",
            name="card_signification_warnings_fr",
            field=models.TextField(default="fr"),
        ),
        migrations.AlterField(
            model_name="majorarcana",
            name="card_signification_work_fr",
            field=models.TextField(default="fr"),
        ),
    ]
