apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-front-deployment" # Name of the deployment with the release name
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-front-deployment"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-front-deployment"
    spec:
      containers:
      - name: "{{ .Release.Name }}-front-container" # Name of the container with the release name
        image: nunoloupy/{{ .Values.frontendlabel }}:latest
        envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-cm"
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
status: {}