name: Build and push images to GitHub Container Registry
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - dev # The release branches
jobs:
  build-and-push-image:    
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
      imageTag: ${{ github.ref_slug }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change directory to app
        run: cd app
      - name: Docker Image build and push to GitHub Container Registry
        uses: NunoMars/docker_image_repo@v1.5
        with:
          file: Dockerfile
          image-name: 'tarot-${{ env.ENVIRONMENT }}'
          tag: ${{ github.ref_slug }}
          context: '.'
          github-token: ${{ secrets.GITHUB_TOKEN}}