name: Build and push images to GitHub Container Registry
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - master # The 'main' branch
      - dev # The release branches
jobs:
  needs: qodana
  build-and-push-image:    
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Image build and push to GitHub Container Registry
        uses: NunoMars/docker_image_repo@v1.5
        with:
          file: Dockerfile
          image: 'tarot-${{ env.ENVIRONMENT }}:${{ github.ref_slug }}'
          tag: ${{ github.ref_slug }}
          context: 'app'
          github-token: ${{ secrets.GITHUB_TOKEN}}