name: Build and push images to GitHub Container Registry
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run python code tets"]
    branches: [main, dev]
    types:
      - completed 

jobs:
  build-and-push-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change directory to app
        run: cd app
      - name: Docker Image build and push to GitHub Container Registry
        uses: NunoMars/docker_image_repo@V2.6 
        with:
          image-name: 'tarot-${{ env.ENVIRONMENT }}'
          password: ${{ secrets.GITHUB_TOKEN}}
          username: ${{ github.actor }}
