name: CI/CD Workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main 
      - dev 

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: VoyanceDB
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt    
      

      - name: Run migrations
        run: |
          cd app
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test

  qodana:
    needs: build
    name: Code Scan for the Tarot App
    if: success()      
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  
          fetch-depth: 0  
       
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        with:         
          pr-mode: false
          args: --apply-fixes
          push-fixes: pull-request          
          commit-message: 'Qodana inspection results'
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

  build-and-push-image:
    needs: qodana
    name: Build and Push Images to GitHub Container Registry
    if: success()  
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change directory to app
        run: cd app
      - name: Docker Image build and push to GitHub Container Registry
        uses: NunoMars/docker_image_repo@V2.6 
        with:
          image-name: 'tarot-${{ env.ENVIRONMENT }}'
          password: ${{ secrets.GITHUB_TOKEN}}
          username: ${{ github.actor }}
